# Generated by Django 5.0.1 on 2024-01-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='specific_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='specific_address',
        ),
    ]
