# Generated by Django 5.0.1 on 2024-02-19 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_order_message_remove_order_payment_id_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name_plural': 'News'},
        ),
        migrations.AddField(
            model_name='news',
            name='title_content',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
