# Generated by Django 5.0.1 on 2024-02-24 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_chartdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChartData',
        ),
    ]
